<?php

namespace App\Http\Controllers;

/**
 * In-app help pages. Two audiences, two static Blade guides:
 *
 *  - parent(): public — how a parent registers, pays, and updates details.
 *  - admin():  behind auth — how staff run the office (lists, allocation,
 *              payment override, CSV).
 *
 * Screenshots live in public/images/help/{parent,admin} and are regenerated by
 * tests/Browser/HelpScreenshotsCapture.php.
 */
class HelpController extends Controller
{
    public function parent()
    {
        return view('help.parent');
    }

    public function admin()
    {
        return view('help.admin');
    }
}
